# Generated by Django 5.0.2 on 2024-02-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='fin_de_plan',
            field=models.DateField(null=True),
        ),
    ]
